(#1539758) tmpfiles: refuse to chown()/chmod() files which are hardlinked, unles…
lnykryn/systemd-rhel pull request #187
Opened 2018-01-29 15:36 UTC by lnykryn

…s protected_hardlinks sysctl is on

Let's add some extra safety.

Fixes: #7736

Cherry-picked from: 5579f85663d10269e7ac7464be6548c99cea4ada
Resolves: #1539758

2018-01-30 11:30 UTC, mrc0mmand commented
Note: changing bug ID from BZ#1539758 (CLOSED WONTFIX) to BZ#1535135 (POST).

2018-02-05 12:48 UTC, msekletar approved these changes

2018-02-05 12:48 UTC, msekletar commented
LGTM

2018-06-12 13:43 UTC, mrc0mmand requested changes

2018-06-12 13:43 UTC, mrc0mmand commented on src/tmpfiles/tmpfiles.c
> +        r = read_one_line_file("/proc/sys/fs/protected_hardlinks", &value);
Probably missing `fileio.h` include for this function.

```
src/tmpfiles/tmpfiles.c: In function 'dangerous_hardlinks':
src/tmpfiles/tmpfiles.c:600:9: error: implicit declaration of function 'read_one_line_file' [-Werror=implicit-function-declaration]
         r = read_one_line_file("/proc/sys/fs/protected_hardlinks", &value);
         ^
```

2018-06-14 13:10 UTC, lnykryn commented
Not needed in el7

2018-06-14 13:10 UTC, closed without merging