core: introduce MemorySwapMax=
lnykryn/systemd-rhel pull request #202
Opened 2018-04-24 09:14 UTC by jsynacek

Similar to MemoryLimit=, MemorySwapMax= limits swap usage. This controls
controls "memory.memsw.limit_in_bytes" attribute in the cgroup hierarchy.

Resolves: #1566177

jsynacek: This still needs to be forward ported to upstream.

2018-04-25 11:09 UTC, jsynacek commented
For the upstream discussion, see https://github.com/systemd/systemd/issues/8814.

2018-05-14 14:21 UTC, msekletar requested changes
Honestly, I am not sure how I feel about this, because it seems to me that in the current form this PR brings substantial inconsistency wrt. upstream behaviour.

If I grok this correctly, then ```MemorySwapMax``` is not really usable w/o setting ```MemoryLimit``` which is not the case in upstream.

2018-05-14 14:21 UTC, msekletar commented on man/systemd.resource-control.xml
> +          <para>Note that even though <literal>memory.memsw.limit_in_bytes</literal> is used, semantics of which is that the value
Remove this paragraph entirely or reword it. Especially, last part sounds confusing to me, because AFAICT ```memory.memsw.limit_in_bytes``` absolute limit as well.

2018-05-14 14:21 UTC, msekletar commented on src/core/load-fragment.c
> +        if (r < 0 || (bytes < 1 && !streq(lvalue, "MemorySwapMax"))) {
Hmm, I am not sure I follow why we treat ```MemorySwapMax``` differently than ```MemoryLimit```.

2018-05-14 14:21 UTC, msekletar commented on src/core/cgroup.c
> +                        uint64_t memsw = c->memory_limit + c->memory_swap_max;
Shouldn't we check for overflow here?

2018-05-15 08:24 UTC, jsynacek commented
>Honestly, I am not sure how I feel about this, because it seems to me that in the current form this PR brings substantial inconsistency wrt. upstream behaviour.

I agree about this. Since upstream doesn't seem to be happy about implementing this, and I absolutely understand that, let's not do this.

2018-05-15 08:24 UTC, closed without merging